// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQy26_ZmXyXbt5pJsw-HH7aCjBTho1A64',
    appId: '1:152322049825:web:34812928c0b2bdc6e4a060',
    messagingSenderId: '152322049825',
    projectId: 'pinky-shop-f5ad6',
    authDomain: 'pinky-shop-f5ad6.firebaseapp.com',
    storageBucket: 'pinky-shop-f5ad6.firebasestorage.app',
    measurementId: 'G-3Z3HG2CW9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV4dt7ne1UFzO1hTVPlPZLNDCcGZbfz5E',
    appId: '1:152322049825:android:a22cdacebae48277e4a060',
    messagingSenderId: '152322049825',
    projectId: 'pinky-shop-f5ad6',
    storageBucket: 'pinky-shop-f5ad6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc4sQvVXAvEmN0Kl3HxoAcPkhrQZ0_e-c',
    appId: '1:152322049825:ios:b719b0a547a6844ce4a060',
    messagingSenderId: '152322049825',
    projectId: 'pinky-shop-f5ad6',
    storageBucket: 'pinky-shop-f5ad6.firebasestorage.app',
    iosBundleId: 'com.example.pinkyShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc4sQvVXAvEmN0Kl3HxoAcPkhrQZ0_e-c',
    appId: '1:152322049825:ios:b719b0a547a6844ce4a060',
    messagingSenderId: '152322049825',
    projectId: 'pinky-shop-f5ad6',
    storageBucket: 'pinky-shop-f5ad6.firebasestorage.app',
    iosBundleId: 'com.example.pinkyShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQy26_ZmXyXbt5pJsw-HH7aCjBTho1A64',
    appId: '1:152322049825:web:19d0a80d9a06d53fe4a060',
    messagingSenderId: '152322049825',
    projectId: 'pinky-shop-f5ad6',
    authDomain: 'pinky-shop-f5ad6.firebaseapp.com',
    storageBucket: 'pinky-shop-f5ad6.firebasestorage.app',
    measurementId: 'G-8KEQ7KYY12',
  );
}
